### ISSUE TITLE
Calendar should be printable one month at a time

### ISSUE THREAD

**Issue by weihenstephaner** [meetburke/CommandSync#145]
As a user, I want to be able to print the command calendar so that I can hand it out to officers that are walking into a calendar scrub meeting.

As a user printing the command calendar, I want to be able to print it one month at a time so that I can organize a readbook in a way that makes sense for my boss.

As a user printing the command calendar, I want an intuitive way to select which month I am going to print so that I don't have to waste paper trying to guess what's going to come out when I start the print job.

As a user printing the command calendar, I want the grid to appear on one page and the event details to appear on another page so that my boss can flip back and forth to see the details for each event that's represented in the grid.

As a user printing the command calendar, I want a legend to appear (horizontally) on the bottom of each grid page so that my boss can tell what he's looking at.  See #184 

As a user printing the command calendar, I want all the days of the month to fit on one page so that the month never appears "cut off".

As a user printing the command calendar, I want to control the portrait or landscape printing of the page so that I can fit the pages into different types of readbooks.

As a user printing the command calendar, I want the categories to overflow "nicely" if there are too many events to fit on one page so that the categories and subcategories still make sense to me if there is a second grid page.

As a user printing the command calendar, I want the events on the "details" pages to appear in the same order that they appear in the calendar so that they are easy to find (i.e. by category and then by start date)

As a user printing the command calendar, I want a matching details page for each grid page that is printed so that it is easy to locate the details for the event that I am looking for on the grid.

------------old details below------------

When requested in the print dialog...

Details for each event should follow the grid segment.
Details are sorted by Start Date. 
Details should include: Start, End, Event Type, Category, Sub-Category, Title, Desc
Font color of event type should match the color scheme
Details should suppress category and subcategory if these are not relevant to the calendar 

------

As a user I want to print 3 months at a time.  I want one month of grid to show up on the first page, and on the second page I want a list of event details. Each set of event details should show start date, end date, description, event type and any other fields.

The details should be grouped by subcategory, then ordered by start date within that.

Dont worry about holidays
 
Always fit all days into the print view, no matter how many days are in the month

Color the event type on the details page IAW legend

Horizontal layout on the bottom for the event type legend

No legend on the details page

if theres a 2nd page, we need another legend for the grid.  in this case we also want to split the details page into 2 at the same place.

**Comment by meetburke** [comment]
Need example screen shot
